# Generated by Django 6.0.2 on 2026-02-26 15:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in months'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1175'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
