# Generated by Django 6.0.2 on 2026-02-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_duration_alter_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
