# Generated by Django 6.0.2 on 2026-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_loan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='principal',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='monthly_installment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='status',
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Defaulted', 'Defaulted')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
